### ISSUE TITLE
Fragment support react v16.2

### ISSUE THREAD

**Issue by djaonourside** [massiveinteractive/haxe-react#85]
It would be great to have a support of Fragment in haxe-react. 
https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

**Comment by djaonourside** [comment]
It should be mentioned here that component 'render' method can also return array of ReactElement. Its annotation should be change to smth like that `function render():EitherType<ReactElement, Array<ReactElement>>;`

**Comment by kLabz** [comment]
This change of signature has been discussed in #80, but since react now supports almost anything from render (string, int, mixed array, etc.) a clean solution hasn't been found yet.

Maybe just allowing `ReactElement` and `Array<ReactElement>`, and use fragments for the rest would do the job.

Edit: sorry about the bad links, an old extension was messing with my browser

**Comment by djaonourside** [comment]
'render' method should also support returning `ReactPortal ` type(https://reactjs.org/docs/react-component.html#render, https://github.com/facebook/react/blob/master/packages/shared/ReactTypes.js).

**Comment by elsassph** [comment]
`ReactDOM.createPortal` API was changed to return a `ReactElement` (because it doesn't really matter) so now it's compatible with `render`.
