### ISSUE TITLE
setState callback typing issue

### ISSUE THREAD

**Issue by elsassph** [massiveinteractive/haxe-react#90]
http://community.haxe.org/t/using-setstate-with-function-in-haxe-react/303/2

Returning a partial object as response of the callback version of setState fails:
```haxe
setState(function(prevState:AppState, props:Dynamic) {
    return { timeLeft: prevState.timeLeft - 1 }; // partial fields of AppState
});
```

**Comment by kLabz** [comment]
setState type is being rewritten by ReactTypeMacro (specifically `getSetStateArgType()` for this) which does something like this : 
```haxe
EitherType<A, EitherType<B, C>>
```
with:
* A = `AppState` -> `Partial<AppState>`
* B = `AppState` -> `PropsType` (`Dynamic` here) -> `Partial<AppState>`
* C = `Partial<AppState>`

We want to unify with B, but somehow this fails although the wanted signature seems correct (to me at least). Should we try overloads instead of `EitherType`s?
